### ISSUE TITLE
支持中文

### ISSUE THREAD

**Issue by nhyilin** [yegor256/huawei.cls#29]
你好，请教一下Mac下如何支持中文，其他格式不变？以我相当有限的经验以及尽可能多的尝试，xeCJK、CJKutf8、ctex，都没能顺利支持。谢谢

**Comment by yegor256** [comment]
I'm using `CJKutf8`:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{CJKutf8}
\begin{document}
\begin{CJK}{UTF8}{gbsn}大家好\end{CJK}}
\end{document}
```

**Comment by nhyilin** [comment]
appreciate with that

**Comment by nhyilin** [comment]
Your solution is good, but it doesn't seem to work for this template, so please advise.
